.TH MU 7 "September 2008" "User Manuals"
.SH NAME 
mu \- collection of utilities for Maildirs, in particular for indexing and
searching.

.SH SYNOPSIS
.B mu-index [
.I options
] [
.I maildir
]

.B mu-find  [options] search-expressions

.SH DESCRIPTION
.B mu
is a collection of utilities to deal with Maildirs, in particular for indexing
and searching messages. Please see the manpages for the individual commands
for details:

.B mu-index
recursively scans a collection of email messages, and stores information
found in a database.

.B mu-find
searches for messages based on some search criteria.

.B mu-msginfo
gives information (such as subject, sender, message body) for a certain
message file

.B mu-mkmdir
creates a new Maildir

.SH BUGS
Please report bugs when you find them.

.SH AUTHOR
Dirk-Jan C. Binnema <djcb@djcbsoftware.nl>

.SH "SEE ALSO"
.BR mu-find (1),
.BR mu-index (1),
.BR mu-mkmdir (1),
.BR mu-msginfo (1),
.BR http://www.djcbsoftware.nl/code/mu

