."-*-mode:nroff-*-"
.TH MU.CONF 5 "August 2008" "User Manuals"
.SH NAME 
mu.conf \- configuration file for the 
.B mu
collection of Maildir utils.

.SH DESCRIPTION
.B mu.conf
is a text file in the mu-home directory which contains configuration settings
for the
.B mu
collection of maildir utilities. Please refer to the manpages for the various
programs for documentation on their particular options.

The configuration file is divided in sections, each starting with [<
.SS sections
.I section name
>]. The section names are the same as the names of the programs they are for;
 e,g, 
.B mu-find
options are found under
.B [mu-find]
and similarly for
.B mu-index
\.
Global settings for all 
.B mu
programs are found under 
.B [mu]

.SS configuration values
The configuration values are of the form:
.B key = value # comment

Anything on a line on the right side of a '#' character, and the '#'-character
itself, are considered comments, and will be ignored.

\. Note that there is no requirement for even having a
.B mu.conf
as the defaults might be sufficient.

.SH FILES
.B mu.conf
can be found in the 
.B .mu/
directory, by default in
.B
$HOME/.mu
.

.SH AUTHOR
Dirk-Jan C. Binnema <djcb@djcbsoftware.nl>

.SH "SEE ALSO"
.BR mu-find (1),
.BR mu-index (1),
.BR mu-mkmdir (1),
.BR mu-msginfo (1),
.BR mu(7)
.BR http://www.djcbsoftware.nl/code/mu

